### ISSUE TITLE
"Back" vs. "Del"

### ISSUE THREAD

**Issue by levone1** [clammet/TraditionalT9#45]
Thank you for this.  Very helpful on my Schok Flip phone.  The stock keyboard is very jumpy/sticky, and this one seems much better.  I have one issue I haven't been able to figure out...

By default, when the keyboard is active, (in a live text field), there is no way to backspace.  The phone's "back" button, which will become "backspace", (del), by default, when typing, doesn't seem to recognize that I am in a text field when I have TraditionalT9 set as default IME., so instead of backspacing, it will navigate back to the previous screen.  I can half-fix it by using your keymap function, making a keymap.txt file containing `4 67`, so now it will del instead of back-navigating, but now, that function is modified globally, so no way to "go back", even when not typing...

I know I could do more complex key-remapping, and get used to different keys doing different things, but I just wondered if you had any better ideas.  Any way maybe to make it so that the keymap mod only applies when in a text field, or...?

**Comment by Clam-** [comment]
I should probably get around to making this repo read only since I don't have any plans to work on it in the future.
I'm not sure if I would be able to help. My phone (Mode 1, MD-02P) also has a single button for clear/back. However, on my phone when I am in a text field (regardless of the IME UI is showing) the clear button backspaces until there is no text then it backs.
I don't use any specific keymap for the clear key, my keymap only has 138->1, 140->2.

I'm sorry that's about all I can help with. Hopefully someone in the community is able to help you out further.
(P.S. by default the keymap does only apply to IME input unless you tick "Translate keys". Perhaps you have accidentally ticked Translate keys)

**Comment by sspanak** [comment]
You may want to try the new upgraded version [here](https://github.com/sspanak/tt9). All functions are fully customizable from the Settings screen, so you could assign the Backspace function to any key you want.

**Comment by Clam-** [comment]
@sspanak, woah, that's a lot of work you've done. Nice job. In a few days I'll make this repo read only and link to your repo in the readme.

Thanks for your efforts.

**Comment by levone1** [comment]
> You may want to try the new upgraded version [here](https://github.com/sspanak/tt9). All functions are fully customizable from the Settings screen, so you could assign the Backspace function to any key you want.

Looks and works beautifully - thank you
